### PR TITLE
Add Linear connector

### PR DESCRIPTION
**Pull request by huongtn**
## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [ #528 ] New feature
- [ ] Breaking change

## Related issues

> Fix [#528]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

### CODE REVIEW

**Comment by thomas-gerber** [comment]
There now is a airbyte linear community source: https://linear.app/docs/airbyte
See conversation here: https://github.com/faros-ai/airbyte-connectors/issues/528. @tovbinm suggested removing our source and just keeping our converters.

**Comment by thomas-gerber** [comment]
Although, it seems the community source does not support incremental yet...

**Comment by thomas-gerber** [comment]
so, maybe we keep our source until we are satisfied with the community source?

**Comment by cjwooo** [comment]
@huongtn Linear already has an Airbyte source for pulling their data. We want to use their version instead of maintaining our own version, but it is missing a couple features that you implemented in your source implementation. The missing features I found so far are: "Labels" stream, and incremental support for "Issues" stream.

We've made a fork of Linear's Airbyte source here https://github.com/faros-ai/linear-airbyte-source. Please make a PR adding those missing features (and any other missing features I missed) to that version of the source, and update your destination converters to support Linear's source. I suspect only minimal changes to the converters will be needed, as the fetched data from each stream should be largely the same.

We can then contribute your source additions upstream to the official Linear source repo.

**Pull request closed without merging**
