### PR TITLE
Update Harness and Pagerduty sources

### PR DESCRIPTION
**Pull request by Roma-Kyrnis**
## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

### CODE REVIEW

**Comment by cjwooo** [comment]
I think we should keep the cutoff parameters. They're useful for users with a lot of source data who don't want to pull all that historical data. If the problem was the cutoff breaking the tests, let's just set the cutoff parameter for testing to an extreme value like 5 years ago or something. @tovbinm

**Comment by tovbinm** [comment]
Yes, we absolutely need to have either cutoff or start date.

**Comment by Roma-Kyrnis** [comment]
Can you add `"cutoff_days": 50000` option to Harness and Pagerduty config?

Do we need to add cutoff to other connectors?

**Comment by tovbinm** [comment]
@Roma-Kyrnis what's the wait here?

**Comment by Roma-Kyrnis** [comment]
I'm updating to main branch and you can merge it

**Review by cjwooo — APPROVED** [review]

**Pull request merged**
