### PR TITLE
Upgrade to Node.js 16

### PR DESCRIPTION
**Pull request by tovbinm**
## Description

Upgrade to Node.js 16

## Type of change
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

### CODE REVIEW

**Review by cjwooo — CHANGES_REQUESTED** [review]
Each source/destination package.json should be updated to indicate the use of version 16 https://github.com/faros-ai/airbyte-connectors/blob/main/sources/example-source/package.json#L18

**Comment by tovbinm** [comment]
Technically, you can still use node 14 to run it. We just package it with Node 16 now.

**Comment by cjwooo** [comment]
If we want to keep supporting 14.x then we should revert this change to the @types/node version https://github.com/faros-ai/airbyte-connectors/pull/542/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R21

**Comment by tovbinm** [comment]
ok, let me bump then

**Comment by tovbinm** [comment]
bumped. we should release it under `0.2.0`

**Review by cjwooo — APPROVED** [review]

**Pull request merged**
