### PR TITLE
Fix use of memoize

### PR DESCRIPTION
**Pull request by cjwooo**
## Description

The typescript-memoize library does not work for generators. Only the first call was yielding results. Therefore, I converted all the functions that utilize the `@Memoize` annotation to return normal lists.

## Type of change
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

### CODE REVIEW

**Review by tovbinm — APPROVED** [review]
bummer that it does not work with AsyncGenerators, oh well.

**Comment by cjwooo** [comment]
Each stream is tested independently so there were no cases yet where the memoized function was called more than once.

**Comment by tovbinm** [comment]
Can we add a test an check that it's being called exactly once? so we could test for memoize being used

**Comment by Roma-Kyrnis** [comment]
I'll try to check. As I understand we need to check that function called exactly only and this function is in AsyncGenerator func?

**Pull request merged**
