### PR TITLE
Bump faros-destination version

### PR DESCRIPTION
**Pull request by ypc-faros**
## Description

Bump version to release latest changes

## Type of change
- [ ] Bug fix
- [X] New feature
- [ ] Breaking change

### CODE REVIEW

**Comment by tovbinm** [comment]
@cjwooo do we have to bump version is all of the connectors or destination is enough?

**Comment by cjwooo** [comment]
just destination should be fine

**Review by tovbinm — APPROVED** [review]

**Comment by tovbinm** [comment]
It should get released now - https://github.com/faros-ai/airbyte-connectors/actions/runs/1860481547

**Comment by ypc-faros** [comment]
Yes, that did it. Thanks!

**Pull request merged**
