### PR TITLE
Add Dockerfile for "incremental" image building

### PR DESCRIPTION
**Pull request by cjwooo**
## Description

> Provide description here

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Related issues

> Fix [#1]() 

## Migration notes

> Describe migration notes if any

## Extra info

> Add any additional information

### CODE REVIEW

**Review by tovbinm — COMMENTED** [review]
Looks like there is a lot of commented out parts. Is this still WIP?

**Comment by cjwooo** [comment]
No. Those are commented out but left in the file so you can choose to run/not run certain steps depending on what you're doing.

**Review by tovbinm — APPROVED** [review]
please add docs on how to use it

**Comment by tovbinm** [comment]
@cjwooo do we still need this?

**Pull request merged**
