### PR TITLE
Pagerduty: Add timezone, role, description and job_title

### LINKED ISSUE #1087: Add timezone to pagerduty user resource
Hi there 👋

We've just started using your super handy Pagerduty connector. I notice that the users record is just the name and email (and a few other standard fields) for the moment.

https://github.com/faros-ai/airbyte-connectors/blob/main/sources/pagerduty-source/src/pagerduty.ts#L60-L63

I'd love to add the time_zone attribute if possible? The role and contact methods attributes would be great too if its not too much trouble?

https://developer.pagerduty.com/api-reference/b3A6Mjc0ODIzMw-list-users

How do enhancements usually get added to the connectors that Faros manage? I can open a PR if its not a priority.

### PR DESCRIPTION
**Pull request by catkins**
## Description

Add some extra properties from the pagerduty users API

https://developer.pagerduty.com/api-reference/b3A6Mjc0ODIzMw-list-users

## Type of change
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

## Related issues

> Fix Resolves #1087

## Migration notes

N/A - non-breaking schema change

### CODE REVIEW

**Comment by catkins** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by catkins** [comment]
recheck

**Comment by catkins** [comment]
recheck

**Review by tovbinm — COMMENTED** [review]
Thanks for adding this! 

Please also update https://github.com/faros-ai/airbyte-connectors/blob/main/sources/pagerduty-source/resources/schemas/users.json. You can do it using this tool - https://www.liquid-technologies.com/online-json-to-schema-converter

**Comment by catkins** [comment]
Thanks @tovbinm, added!

**Comment by catkins** [comment]
recheck

**Review by tovbinm — APPROVED** [review]

**Pull request merged**
