### PR TITLE
FAI-13924: Fix stream filtering

### PR DESCRIPTION
**Pull request by chalenge**
## Description

- Should use snakecase names

## Type of change
- [X] Bug fix
- [ ] New feature
- [ ] Breaking change

### CODE REVIEW

**Comment by ypc-faros** [comment]
I'm surprised you need to do this. See the impl for `name` : https://github.com/faros-ai/airbyte-connectors/blob/e763191a928ba4ed1b8b2c420f5eb406a690cf0f/faros-airbyte-cdk/src/sources/streams/stream-base.ts#L23

**Comment by ypc-faros** [comment]
Maybe a test would help figure out what's going on. See [here](https://github.com/faros-ai/airbyte-connectors/blob/e763191a928ba4ed1b8b2c420f5eb406a690cf0f/sources/jira-source/test/index.test.ts#L757-L764) for an example

**Comment by chalenge** [comment]
> I'm surprised you need to do this. See the impl for `name` :
> 
> https://github.com/faros-ai/airbyte-connectors/blob/e763191a928ba4ed1b8b2c420f5eb406a690cf0f/faros-airbyte-cdk/src/sources/streams/stream-base.ts#L23

That would only work if I had instantiated the class `new Users(config, this.logger)`, that was the bug otherwise it returns the JavaScript's built-in name property of a class. Not worth instantiate a whole class for a name here.

**Comment by ypc-faros** [comment]
> > I'm surprised you need to do this. See the impl for `name` :
> > https://github.com/faros-ai/airbyte-connectors/blob/e763191a928ba4ed1b8b2c420f5eb406a690cf0f/faros-airbyte-cdk/src/sources/streams/stream-base.ts#L23
> 
> That would only work if I had instantiated the class `new Users(config, this.logger)`, that was the bug otherwise it returns the JavaScript's built-in name property of a class. Not worth instantiating a whole class for a name here. Added test

OMG, js!!! 🤦‍♂️

**Review by ypc-faros — APPROVED** [review]

**Pull request merged**
